import Head from 'next/head';

import { MainLayout } from '~/layout/MainLayout/MainLayout';

export default function Home() {
  // const { data } = useQuery({
  //   queryFn: () => fetchFilms.top({ type: 'TOP_AWAIT_FILMS' }),
  //   queryKey: ['top-list'],
  // });
  //
  // console.log(data?.films);

  return (
    <>
      <Head>
        <title>KindKino</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <MainLayout />
    </>
  );
}
